### ISSUE TITLE
Disable on mobile or small screen

### ISSUE THREAD

**Issue by timrombergjakobsson** [imgix/drift#56]
Hi! Is there any option for disabling Drift on say a mobile device or smaller screen? Thanks in advance!

**Comment by frederickfogerty** [comment]
Hey @timrombergjakobsson 👋 

Fred from Imgix here. I'm responsible for maintaining this repo from today onwards. At the moment a workaround is to override the CSS of the `drift` component:

```css
@media (max-width: 610px) {

  .drift-zoom-pane.drift-open, .drift-zoom-pane {
    display: none;
  }

}
```
